name: Continuous Deploy

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout target
      uses: actions/checkout@v2
      with:
          repository: etosis/etosis.com.staging
          path: _site
          token: ${{ secrets.ETOSIS_COM_STAGING_TOKEN }}
          ref: "main"
          fetch-depth: 1
    
    - name: Build
      run: |
        npm install
        npx @11ty/eleventy
          
    - name: Commit to staging
      working-directory: ./_site
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@etosis.com
        git add .
        git commit -m "Update"
        git push
        
